#!/bin/sh
# Need to look at vim plugin install
set -e 

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.profile" "$HOME/.bash_profile" # Not sure if needed
ln -sf "$PWD/scripts" "$HOME/Scripts" 

for i in vim lynx tmux scripts screen; do # should probably make sure scripts is always last in this list
    cd $i && ./setup${i}
    cd - 
done

