#!/bin/sh
set -e 

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.profile" "$HOME/.bash_profile" # Not sure if needed
# ln -sf "$PWD/scripts" "$HOME/Scripts" 
# Maybe set symbolic links from HOME/SCRIPTS to .local/bin?

for i in vim lynx tmux; do 
    cd $i && ./setup
    cd - 
done
