#!/bin/sh 

# libcruses and cpan term:animation is for fishes 
# Larger overhead but fun to try out script
sudo apt install nmap lynx tmux python-is-python3 pip curl entr bash-completion net-tools libcurses-perl
sudo cpan -I Term::Animation
