#!/usr/bin/env bash 
# Maybe look into loading the vim setup script or pluginstall command automatically 
# Need to run vim and load the plugins also
# have the script vimplugininstall 
# Need to look when path is established and auto run it

if [[ -z "$(which vim)" || -z "$(which vimtutor)" ]]; then 
    echo "Does not look like full vim is installed"
fi

ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
mkdir -p "$HOME/.vim/autoload"
ln -sf "$PWD/.vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"


