#!/bin/bash
set -e

user=charmbracelet
repo=mods

arch=$(uname -m)

latest="https://api.github.com/repos/$user/$repo/releases/latest"
url=$(curl -s "$latest" | jq -r --arg arch "$arch" '.assets[].browser_download_url | select(endswith(".rpm") and contains($arch))')
ver=${url##*/}


dir="$(mktemp -d)"
echo "$dir"
cd "$dir"
curl -LO "$url" && sudo rpm -i "$ver"

