#!/bin/sh 

# libcruses and cpan term:animation is for fishes 
# Larger overhead but fun to try out script
sudo dnf install -y shellcheck dnf-utils lynx tmux python-is-python3 pip curl bash-completion net-tools
