#!/bin/sh

# Might be able to add to grab single topic like cheat.sh/tar
# If statement that will call the function if needed (two args) vs not if just a single arg
# Right now can pull down for specific topics 
# example cheat python :list (list all the options for python
  
cheat() {
  where="$1"
  if [ $# -ge 1 ]; then
    shift
  fi
  IFS=+ curl -sS "http://cht.sh/$where/$*"
}

cheat "$@"


