#!/usr/bin/env bash
# Credit RWXrob beginner boost and dot file

#exec w3m "duckduckgo.com/lite?kd=-1&kp=-1&q=$*"
url="https://lite.duckduckgo.com/lite?kd=-1&kp=-1&q=$(urlencode "$*")" # 
exec lynx "$url"
#exec w3m "$url"
#exec lynx "duckduckgo.com/lite?q=$*" # 
#exec lynx "duckduckgo.com/lite?q=$*"

