#!/usr/bin/env bash 
##################################################################
# Purpose: Run against group of dirs and do git pull or git status
# Date: 07/02/2024
# Author: Stephen Sparks
# Revisions:
#################################################################
# TODOs 
# Maybe a check to make sure that you are running it in the right dir/area
# add alittle color for the cd break it up alittle better
# run on directories that contain directories that are git repos 
# for i in *; do cd $i; git status; echo ""; cd ..;done 

black=$'\e[30m'
red=$'\e[31m'
green=$'\e[32m'
yellow=$'\e[33m'
blue=$'\e[34m'
magenta=$'\e[35m'
cyan=$'\e[36m'
white=$'\e[37m'
reset=$'\e[0m'

gitrun(){
    local input=$1
    for i in *; do 
        cd "$i" || { echo "cd failed"; exit 1; }
        git "$input"
        echo ""
        cd ..
    done
}

if [[ $1 == "pull" ]]; then
    gitrun "pull"
elif [[ $1 == "status" ]]; then # Add a OR statment to check for no options passed
    gitrun "status"
else # Else should be an error that explains how to use the gitcheck pull/status
    gitrun "status"
fi

