#!/usr/bin/env bash
# Credit RWXrob beginner boost and dot file
# Requires mods charmbracelet/mods

_have() { type "$1" &>/dev/null; }

declare OPENAI_API_KEY
OPENAI_API_KEY="$(head -1 "$HOME/.config/gpt/token")"
export OPENAI_API_KEY

! _have mods && echo "requires charmbracelet/mods" && exit 1
#    mods "$*"
    mods --status-text "Ummm" "$*"

