#!/usr/bin/env bash
# Credit RWXrob beginner boost and dot file
# Requires mods charmbracelet/mods

# Made changes but did not exclude the export of the custom token file 
# Look at mods --settings and can modify the .yaml file directly with the Token?

_have() { type "$1" &>/dev/null; }

declare OPENAI_API_KEY
OPENAI_API_KEY="$(head -1 "$HOME/.config/gpt/token")"
export OPENAI_API_KEY

! _have mods && echo "requires charmbracelet/mods" && exit 1
#    mods "$*" # problem is show does not pass the hash or continue 
if [[ "$1" == "list" ]]; then # if first arg is list then run --list on mods
    mods --list 
elif [[ "$1" == "show" ]]; then # if show and hash is passed run mod --show with hash
    mods --show "$2"
elif [[ "$1" == "cont" ]]; then 
    shift #remove the cont arg
    hash="$1" #save the hash
    shift # remove the hash
    mods --continue "$hash" "$*" # pass the hash and the rest of the prompt to continue 
else
    mods --status-text "Ummm" "$*" ## OG Line that runs 
fi

# Do we need to have a error to show proper useage?
# Looks to be a short hand for list and other might be more useful to pass -l instead of just list as an arg to ??
# ?? show hash (run mods --show hash
# ?? list (runs mods --list)

# mods --list (shows all)
# mods --show hash (shows the specific convo)
