#!/usr/bin/env bash
# Credit RWXrob beginner boost and dot file
# Requires mods charmbracelet/mods

# Made changes but did not exclude the export of the custom token file 
# Look at mods --settings and can modify the .yaml file directly with the Token?

_have() { type "$1" &>/dev/null; }

declare OPENAI_API_KEY
OPENAI_API_KEY="$(head -1 "$HOME/.config/gpt/token")"
export OPENAI_API_KEY

! _have mods && echo "requires charmbracelet/mods" && exit 1
#    mods "$*"
    mods --status-text "Ummm" "$*"

# Mods saves the convos like git 
# mods --list (shows all)
# mods --show hash (shows the specific convo)
# maybe mixes those in here
# Don't totally over complicate
