#!/usr/bin/env bash 

# Script to quickly grab system information
# Include: 
# HOSTNAME
# CPU info 
# uptime
# Hardware info 
# Kernel info 
# Maybe number of kernel files in boot 
# Number of packages? 
# RAM and disk info 
# swap info 
# Distro 
# virt info 
# maybe netwwork info

_hostname() { 
    hostname="$(hostnamectl | grep hostname | awk '{print $3}')"
} 

_architecture() {
    architecture="$(uname -m)"
}

_cpu_count() {
    cpuCount="$(grep -ic processor /proc/cpuinfo)"
}

_uptime() {
    uptime="System $(uptime --pretty)"
}


_hostname 
_uptime 
_architecture
_cpu_count 

printf "%s\n" \
    "$hostname" \
    "$uptime" \
    "$architecture" \
    "$cpuCount"
