#!/usr/bin/env bash 

# Script to quickly grab system information
# Include: 
# Number of packages? Should we determine what package manager is being used? needs some logic
# RAM and disk info 
# swap info 
# virt info otherways besides hostnamectl vendor and model for this

_hostname() { 
    hostname="$(hostnamectl | grep hostname | awk '{print $3}')"
} 

_architecture() {
    architecture="$(uname -m)"
}

_boot_loader_call() {
    cmdline="$(cat /proc/cmdline)"
}

_cpu_count() {
    cpuCount="$(nproc)"
}

_uptime() {
    uptime="System $(uptime --pretty)"
}

_kernel(){
    kernel="$(uname -r)"
    # some better ones might be hostnamectl or cat /etc/*release
}

_start_up_time(){
    startup="$(systemd-analyze time)"
}

_distro_name() {
    distro="$(hostnamectl | grep -i system | cut -d':' -f2)"
}

_hardware(){ # Need to better format this 
    hardware_vendor="H/W Vendor:$(hostnamectl | grep -i vendor | cut -d':' -f2)"
    hardware_model="H/W Model:$(hostnamectl | grep -i model | cut -d':' -f2)"
}    

_packages(){ # Look to add more pack managers later
    # Should we run the command to /dev/null and then capture the exit code?
    command -v apt > /dev/null 2>&1 
    apt_system=$?
    command -v dnf > /dev/null 2>&1 
    dnf_system=$?
    command -v pacman > /dev/null 2>&1 
    pacman_system=$?

    if [[ $apt_system -eq 0 ]];then 
        total_packages=$(apt list installed | sort | uniq | wc -l)
    elif [[ dnf_system -eq 0 ]]; then 
        total_packages=$(dnf list installed | sort | uniq | wc -l)
    elif [[ $pacman_system  -eq 0 ]]; then 
        total_packages=$(pacman -Q | sort | uniq | wc -l) 
    else 
        total_packages="Specific # of packages not found"
    fi

}



_hostname 
_uptime 
_architecture
_cpu_count 
_boot_loader_call
_kernel 
_start_up_time
_distro_name
_hardware
_packages

echo ""
printf "%s\n" \
    "Hostname: $hostname" \
    "$uptime" \
    "Distro Name:$distro" \
    "Kernel: $kernel" \
    "$cmdline" \
    "Architecture: $architecture" \
    "CPUs: $cpuCount" \
    "$startup" \
    "$hardware_vendor" \
    "$hardware_model" \
    "Packages: $total_packages"
echo ""
