#!/usr/bin/env bash 

# Make sure to throw an errow if a number is not passed and show proper usage (as of now)
# Take first and second variable as numbers and increament by 50 to ping yahoo
# Break this up and make it more functional rather than a simple one liner
# maybe test for a third arg and let the domain be passed?
# maybe turn into a function and then the conditional stands alone?

for i in `seq $1 50 $2`; do ping -c1 -s $i -M do yahoo.com; done

# ping -c1 one time 
# -s (for size)
# -M for pmtudisc_option (do set the do not fragment bit)
# Might want to throw a check that something is passed to (look at what happens when run and no args are passed)
