#!/usr/bin/env bash 

# Just need to convert epoch to a date (everything else is extra)

if [[ $# -eq 1 ]]; then 
    date --date=@"${1}"
elif [[ $# -eq 0 ]]; then 
    date +'%s'
    echo 
    printf "Common useage:\n"
    printf "For unix to human conversion: unixtime epoch\n"
    printf "For date to epoch: unixtime MM/DD/YYYY HH:MM:SS (24 Hour Time)\n"
    echo
elif [[ $# -eq 2 ]]; then 
    date -d "${1} ${2}" +"%s"
else
    printf "Command not run\n"
    printf "For unix to human conversion: unixtime epoch\n"
    printf "For date to epoch: unixtime MM/DD/YYYY HH:MM:SS (24 Hour Time)\n"
    echo
fi
# date -d "06/10/2024 07:21:23" +"%s"
# date --date=@1718004083
# Time zone considerations?

