#!/usr/bin/env bash 

# Look into checking the domain as well (strip to the root domain on all cases)

if command -v whois >/dev/null 2>&1 ; then # quick check to see if whois is on the system
        echo ""
    else
        echo "It does not look like the whois command is on this system"
        exit
    fi

if [[ "$2" == "full" ]]; then # If domain is passed and second arg is full 
    whois "$1" 
    echo ""
elif [[ "$#" -eq 2 ]]; then # if there are two args pass the second to grep
    whois "$1" | grep -i "$2"
    echo ""
elif [[ "$#" -eq 1 ]]; then # if only one arg (assuming domain) pull the registrar 
    whois "$1" | grep -i "registrar"
    echo ""
else # Should only run if 0 or 3 or more args are passed
    printf "Something went wrong\n"
    printf "try: whodot DOMAIN [grep_string]\n"
    printf "without grep string it will return registrar info\n"
    printf "whodot DOMAIN full (will return the full whois query)\n"
    printf "can pass in the domain and the arg full to see full whois listing (same as whois DOMAIN)\n"
    echo ""
fi



