#!/bin/sh

# Requires lynx script (and optional ? alias tied to duck)
# Special thanks to rwxrob/dot twitch.tv/rwxrob

mkdir ~/.config/ 2>/dev/null
rm -rf ~/.config/lynx 2>/dev/null
ln -sf "$PWD/lynx.cfg" "$HOME/.config/lynx/lynx.cfg"
ln -sf "$PWD/lynx.cfg" "$HOME/.config/lynx/lynx.lss"
ls -l ~/.config/lynx 
